### ISSUE TITLE
build failure with python 3.10 prerelease

### ISSUE THREAD

**Issue by belegdol** [missinglinkelectronics/sphinxcontrib-svg2pdfconverter#14]
Build failure with python-3.10a4 was reported for Fedora:
```

Traceback (most recent call last):
  File "/builddir/build/BUILD/sphinxcontrib-svg2pdfconverter-1.1.1/setup.py", line 14, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 232, in run
    self.run_tests()
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 250, in run_tests
    test = unittest.main(
  File "/usr/lib64/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.10/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib64/python3.10/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib64/python3.10/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.10/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.10/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib64/python3.10/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 42, in loadTestsFromModule
    for file in resource_listdir(module.__name__, ''):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1147, in resource_listdir
    return get_provider(package_or_requirement).resource_listdir(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 349, in get_provider
    return _find_adapter(_provider_factories, loader)(module)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1378, in __init__
    self.module_path = os.path.dirname(getattr(module, '__file__', ''))
  File "/usr/lib64/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
https://bugzilla.redhat.com/show_bug.cgi?id=1914879

**Comment by tirkarthi** [comment]
This is likely due to using python setup.py test. See : https://github.com/pypa/setuptools/issues/1827 . Can you please share the command used to run tests?

**Comment by belegdol** [comment]
The full build log is here:
https://download.copr.fedorainfracloud.org/results/@python/python3.10/fedora-rawhide-x86_64/01916492-python-sphinxcontrib-svg2pdfconverter/builder-live.log.gz
```
+ /usr/bin/python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing sphinxcontrib_svg2pdfconverter.egg-info/PKG-INFO
writing dependency_links to sphinxcontrib_svg2pdfconverter.egg-info/dependency_links.txt
writing namespace_packages to sphinxcontrib_svg2pdfconverter.egg-info/namespace_packages.txt
writing requirements to sphinxcontrib_svg2pdfconverter.egg-info/requires.txt
writing top-level names to sphinxcontrib_svg2pdfconverter.egg-info/top_level.txt
reading manifest file 'sphinxcontrib_svg2pdfconverter.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'sphinxcontrib_svg2pdfconverter.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "/builddir/build/BUILD/sphinxcontrib-svg2pdfconverter-1.1.1/setup.py", line 14, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 232, in run
    self.run_tests()
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 250, in run_tests
    test = unittest.main(
  File "/usr/lib64/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.10/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib64/python3.10/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib64/python3.10/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.10/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.10/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib64/python3.10/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.10/site-packages/setuptools/command/test.py", line 42, in loadTestsFromModule
    for file in resource_listdir(module.__name__, ''):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1148, in resource_listdir
    return get_provider(package_or_requirement).resource_listdir(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 349, in get_provider
    return _find_adapter(_provider_factories, loader)(module)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1379, in __init__
    self.module_path = os.path.dirname(getattr(module, '__file__', ''))
  File "/usr/lib64/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
error: Bad exit status from /var/tmp/rpm-tmp.ngkuPr (%check)
    Bad exit status from /var/tmp/rpm-tmp.ngkuPr (%check)
```

**Comment by belegdol** [comment]
I have disabled tests for now. Were there any in the first place?

**Comment by sephalon** [comment]
As already indicated in the log you posted and according to [this issue](https://github.com/pypa/setuptools/issues/931), `setup.py test` is deprecated:

> ```
> + /usr/bin/python3 setup.py test
> running test
> WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
> …
> ```

Although there is a dummy tox config, there are no tests anyway as of now. Closed.
